import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'DoughnutChart',
  title: '环形图',
  version: '1.0.0',
  category: '图表',
  props: {
    title: {
      name: 'title',
      label: '图表标题',
      setter: 'StringSetter',
      defaultValue: '',
      group: '基础',
    },
    titleAlign: {
      name: 'titleAlign',
      label: '标题对齐',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
      },
      defaultValue: 'center',
      group: '基础',
    },
    titleSize: {
      name: 'titleSize',
      label: '标题字号',
      setter: 'NumberSetter',
      defaultValue: 16,
      group: '基础',
    },
    titleColor: {
      name: 'titleColor',
      label: '标题颜色',
      setter: 'ColorSetter',
      defaultValue: '#333',
      group: '基础',
    },
    seriesName: {
      name: 'seriesName',
      label: '系列名称',
      setter: 'StringSetter',
      defaultValue: 'Access From',
      group: '基础',
    },
    showLegend: {
      name: 'showLegend',
      label: '显示图例',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '图例',
    },
    legendOrient: {
      name: 'legendOrient',
      label: '图例方向',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
      },
      defaultValue: 'horizontal',
      group: '图例',
    },
    legendLeft: {
      name: 'legendLeft',
      label: '图例水平位置',
      setter: 'StringSetter',
      defaultValue: 'center',
      group: '图例',
    },
    legendTop: {
      name: 'legendTop',
      label: '图例垂直位置',
      setter: 'StringSetter',
      defaultValue: 'bottom',
      group: '图例',
    },
    showLabel: {
      name: 'showLabel',
      label: '显示标签',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '标签',
    },
    labelFormatter: {
      name: 'labelFormatter',
      label: '标签格式',
      setter: 'StringSetter',
      defaultValue: '{b}: {c}',
      description: '支持 {a}系列名 {b}数据名 {c}数值 {d}百分比',
      group: '标签',
    },
    showLabelLine: {
      name: 'showLabelLine',
      label: '显示标签线',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '标签',
    },
    innerRadius: {
      name: 'innerRadius',
      label: '内半径',
      setter: 'StringSetter',
      defaultValue: '40%',
      group: '样式',
    },
    outerRadius: {
      name: 'outerRadius',
      label: '外半径',
      setter: 'StringSetter',
      defaultValue: '70%',
      group: '样式',
    },
    centerX: {
      name: 'centerX',
      label: '中心X位置',
      setter: 'StringSetter',
      defaultValue: '50%',
      group: '样式',
    },
    centerY: {
      name: 'centerY',
      label: '中心Y位置',
      setter: 'StringSetter',
      defaultValue: '50%',
      group: '样式',
    },
    borderRadius: {
      name: 'borderRadius',
      label: '圆角',
      setter: 'NumberSetter',
      defaultValue: 10,
      group: '样式',
    },
    borderColor: {
      name: 'borderColor',
      label: '边框颜色',
      setter: 'ColorSetter',
      defaultValue: '#fff',
      group: '样式',
    },
    borderWidth: {
      name: 'borderWidth',
      label: '边框宽度',
      setter: 'NumberSetter',
      defaultValue: 2,
      group: '样式',
    },
    data: {
      name: 'data',
      label: '数据',
      setter: 'JsonSetter',
      defaultValue: [
        { name: '类型A', value: 335 },
        { name: '类型B', value: 234 },
        { name: '类型C', value: 154 },
      ],
      group: '数据',
    },
    option: {
      name: 'option',
      label: '高级配置(JSON)',
      setter: 'JsonSetter',
      defaultValue: {},
      group: '高级',
    },
  },
  events: [],
  defaultSize: {
    width: 400,
    height: 300,
  },
}

export default meta
