import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'ScatterChart',
  title: '散点图',
  version: '1.0.0',
  category: '图表',
  props: {
    title: {
      name: 'title',
      label: '图表标题',
      setter: 'StringSetter',
      defaultValue: '',
      group: '基础',
    },
    titleAlign: {
      name: 'titleAlign',
      label: '标题对齐',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
      },
      defaultValue: 'center',
      group: '基础',
    },
    titleSize: {
      name: 'titleSize',
      label: '标题字号',
      setter: 'NumberSetter',
      defaultValue: 16,
      group: '基础',
    },
    titleColor: {
      name: 'titleColor',
      label: '标题颜色',
      setter: 'ColorSetter',
      defaultValue: '#333',
      group: '基础',
    },
    seriesName: {
      name: 'seriesName',
      label: '系列名称',
      setter: 'StringSetter',
      defaultValue: 'Data',
      group: '基础',
    },
    showLegend: {
      name: 'showLegend',
      label: '显示图例',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '图例',
    },
    legendLeft: {
      name: 'legendLeft',
      label: '图例水平位置',
      setter: 'StringSetter',
      defaultValue: 'center',
      group: '图例',
    },
    legendTop: {
      name: 'legendTop',
      label: '图例垂直位置',
      setter: 'StringSetter',
      defaultValue: 'bottom',
      group: '图例',
    },
    symbolSize: {
      name: 'symbolSize',
      label: '点大小',
      setter: 'NumberSetter',
      defaultValue: 10,
      group: '样式',
    },
    color: {
      name: 'color',
      label: '点颜色',
      setter: 'ColorSetter',
      defaultValue: '#5470c6',
      group: '样式',
    },
    opacity: {
      name: 'opacity',
      label: '透明度',
      setter: 'SliderSetter',
      setterProps: {
        min: 0,
        max: 1,
        step: 0.1,
      },
      defaultValue: 0.8,
      group: '样式',
    },
    gridLeft: {
      name: 'gridLeft',
      label: '网格左侧',
      setter: 'StringSetter',
      defaultValue: '10%',
      group: '网格',
    },
    gridRight: {
      name: 'gridRight',
      label: '网格右侧',
      setter: 'StringSetter',
      defaultValue: '10%',
      group: '网格',
    },
    gridBottom: {
      name: 'gridBottom',
      label: '网格底部',
      setter: 'StringSetter',
      defaultValue: '15%',
      group: '网格',
    },
    gridTop: {
      name: 'gridTop',
      label: '网格顶部',
      setter: 'StringSetter',
      defaultValue: '15%',
      group: '网格',
    },
    xAxisName: {
      name: 'xAxisName',
      label: 'X轴名称',
      setter: 'StringSetter',
      defaultValue: '',
      group: '坐标轴',
    },
    yAxisName: {
      name: 'yAxisName',
      label: 'Y轴名称',
      setter: 'StringSetter',
      defaultValue: '',
      group: '坐标轴',
    },
    showXAxisSplitLine: {
      name: 'showXAxisSplitLine',
      label: '显示X轴分割线',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    showYAxisSplitLine: {
      name: 'showYAxisSplitLine',
      label: '显示Y轴分割线',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    data: {
      name: 'data',
      label: '数据',
      setter: 'JsonSetter',
      defaultValue: [
        [10.0, 8.04],
        [8.0, 6.95],
        [13.0, 7.58],
        [9.0, 8.81],
        [11.0, 8.33],
        [14.0, 9.96],
        [6.0, 7.24],
        [4.0, 4.26],
        [12.0, 10.84],
        [7.0, 4.82],
        [5.0, 5.68],
      ],
      group: '数据',
    },
    option: {
      name: 'option',
      label: '高级配置(JSON)',
      setter: 'JsonSetter',
      defaultValue: {},
      group: '高级',
    },
  },
  events: [],
  defaultSize: {
    width: 400,
    height: 300,
  },
}

export default meta
