import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'NumberInput',
  title: '数字输入',
  version: '1.0.0',
  category: '表单',
  props: {
    value: {
      name: 'value',
      label: '当前值',
      title: '当前值',
      setter: 'NumberSetter',
      defaultValue: 0,
      group: '基础',
    },
    placeholder: {
      name: 'placeholder',
      label: '占位文本',
      title: '占位文本',
      setter: 'StringSetter',
      defaultValue: '请输入数字',
      group: '基础',
    },
    min: {
      name: 'min',
      label: '最小值',
      title: '最小值',
      setter: 'NumberSetter',
      defaultValue: 0,
      group: '交互',
    },
    max: {
      name: 'max',
      label: '最大值',
      title: '最大值',
      setter: 'NumberSetter',
      defaultValue: 100,
      group: '交互',
    },
    step: {
      name: 'step',
      label: '步长',
      title: '步长',
      setter: 'NumberSetter',
      defaultValue: 1,
      group: '交互',
    },
    precision: {
      name: 'precision',
      label: '小数位',
      title: '小数位',
      setter: 'NumberSetter',
      defaultValue: 0,
      group: '交互',
    },
    controls: {
      name: 'controls',
      label: '显示步进按钮',
      title: '显示步进按钮',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '交互',
    },
    disabled: {
      name: 'disabled',
      label: '禁用',
      title: '禁用',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '交互',
    },
    size: {
      name: 'size',
      label: '尺寸',
      title: '尺寸',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      defaultValue: 'default',
      group: '样式',
    },
    inputWidth: {
      name: 'inputWidth',
      label: '输入框宽度',
      title: '输入框宽度',
      setter: 'NumberSetter',
      defaultValue: 100,
      description: '宽度百分比 (0-100)',
      group: '尺寸',
    },
    padding: {
      name: 'padding',
      label: '内边距',
      title: '内边距',
      setter: 'NumberSetter',
      defaultValue: 8,
      group: '尺寸',
    },
    backgroundColor: {
      name: 'backgroundColor',
      label: '背景颜色',
      title: '背景颜色',
      setter: 'ColorSetter',
      defaultValue: 'transparent',
      group: '样式',
    },
    borderRadius: {
      name: 'borderRadius',
      label: '圆角',
      title: '圆角',
      setter: 'NumberSetter',
      defaultValue: 4,
      group: '样式',
    },
    opacity: {
      name: 'opacity',
      label: '不透明度',
      title: '不透明度',
      setter: 'SliderSetter',
      setterProps: {
        min: 0,
        max: 100,
        step: 1,
      },
      defaultValue: 100,
      group: '样式',
    },
  },
  events: ['onChange'],
  defaultSize: {
    width: 220,
    height: 40,
  },
}

export default meta
