import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'BarChart',
  componentName: 'BarChart',
  title: '柱状图',
  version: '1.0.0',
  category: '图表',
  props: {
    title: {
      name: 'title',
      label: '图表标题',
      title: '图表标题',
      setter: 'StringSetter',
      defaultValue: '',
    },
    seriesName: {
      name: 'seriesName',
      label: '系列名称',
      title: '系列名称',
      setter: 'StringSetter',
      defaultValue: 'Series',
    },
    showLegend: {
      name: 'showLegend',
      label: '显示图例',
      title: '显示图例',
      setter: 'BooleanSetter',
      defaultValue: true,
    },
    legendPosition: {
      name: 'legendPosition',
      label: '图例位置',
      title: '图例位置',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '顶部', value: 'top' },
          { label: '底部', value: 'bottom' },
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
        ],
      },
      defaultValue: 'top',
    },
    showTooltip: {
      name: 'showTooltip',
      label: '显示提示',
      title: '显示提示',
      setter: 'BooleanSetter',
      defaultValue: true,
    },
    showGrid: {
      name: 'showGrid',
      label: '显示网格',
      title: '显示网格',
      setter: 'BooleanSetter',
      defaultValue: true,
    },
    showLabel: {
      name: 'showLabel',
      label: '显示标签',
      title: '显示标签',
      setter: 'BooleanSetter',
      defaultValue: false,
    },
    barColor: {
      name: 'barColor',
      label: '柱子颜色',
      title: '柱子颜色',
      setter: 'ColorSetter',
      defaultValue: '#409eff',
    },
    barWidth: {
      name: 'barWidth',
      label: '柱宽度',
      title: '柱宽度',
      setter: 'StringSetter',
      defaultValue: '60%',
    },
    borderRadius: {
      name: 'borderRadius',
      label: '柱圆角',
      title: '柱圆角',
      setter: 'NumberSetter',
      defaultValue: 0,
    },
    xAxisName: {
      name: 'xAxisName',
      label: 'X轴名称',
      title: 'X轴名称',
      setter: 'StringSetter',
      defaultValue: '',
    },
    yAxisName: {
      name: 'yAxisName',
      label: 'Y轴名称',
      title: 'Y轴名称',
      setter: 'StringSetter',
      defaultValue: '',
    },
    xAxisData: {
      name: 'xAxisData',
      label: 'X轴数据',
      title: 'X轴数据',
      setter: 'JsonSetter',
      defaultValue: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    },
    data: {
      name: 'data',
      label: '数据',
      title: '数据',
      setter: 'JsonSetter',
      defaultValue: [120, 200, 150, 180, 270, 210, 220],
    },
    option: {
      name: 'option',
      label: '高级配置(JSON)',
      title: '高级配置(JSON)',
      setter: 'JsonSetter',
      defaultValue: {},
    },
  },
  events: [],
}

export default meta
