import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'LineChart',
  title: '折线图',
  version: '1.0.0',
  category: '图表',
  props: {
    title: {
      name: 'title',
      label: '图表标题',
      setter: 'StringSetter',
      defaultValue: '',
      group: '基础',
    },
    seriesName: {
      name: 'seriesName',
      label: '系列名称',
      setter: 'StringSetter',
      defaultValue: 'Series',
      group: '基础',
    },
    showLegend: {
      name: 'showLegend',
      label: '显示图例',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '图例',
    },
    legendPosition: {
      name: 'legendPosition',
      label: '图例位置',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '顶部', value: 'top' },
          { label: '底部', value: 'bottom' },
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
        ],
      },
      defaultValue: 'top',
      group: '图例',
    },
    showTooltip: {
      name: 'showTooltip',
      label: '显示提示',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '交互',
    },
    showGrid: {
      name: 'showGrid',
      label: '显示网格',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    showSymbol: {
      name: 'showSymbol',
      label: '显示标记点',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '样式',
    },
    symbolSize: {
      name: 'symbolSize',
      label: '标记点大小',
      setter: 'NumberSetter',
      defaultValue: 6,
      group: '样式',
    },
    smooth: {
      name: 'smooth',
      label: '平滑曲线',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '样式',
    },
    showArea: {
      name: 'showArea',
      label: '区域填充',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '样式',
    },
    areaOpacity: {
      name: 'areaOpacity',
      label: '填充透明度',
      setter: 'SliderSetter',
      setterProps: {
        min: 0,
        max: 1,
        step: 0.1,
      },
      defaultValue: 0.3,
      group: '样式',
    },
    lineColor: {
      name: 'lineColor',
      label: '线条颜色',
      setter: 'ColorSetter',
      defaultValue: '#409eff',
      group: '样式',
    },
    lineWidth: {
      name: 'lineWidth',
      label: '线条宽度',
      setter: 'NumberSetter',
      defaultValue: 2,
      group: '样式',
    },
    lineType: {
      name: 'lineType',
      label: '线条类型',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '实线', value: 'solid' },
          { label: '虚线', value: 'dashed' },
          { label: '点线', value: 'dotted' },
        ],
      },
      defaultValue: 'solid',
      group: '样式',
    },
    xAxisName: {
      name: 'xAxisName',
      label: 'X轴名称',
      setter: 'StringSetter',
      defaultValue: '',
      group: '坐标轴',
    },
    yAxisName: {
      name: 'yAxisName',
      label: 'Y轴名称',
      setter: 'StringSetter',
      defaultValue: '',
      group: '坐标轴',
    },
    showXAxisLine: {
      name: 'showXAxisLine',
      label: '显示X轴线',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    showXAxisLabel: {
      name: 'showXAxisLabel',
      label: '显示X轴标签',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    showYAxisLine: {
      name: 'showYAxisLine',
      label: '显示Y轴线',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    showYAxisLabel: {
      name: 'showYAxisLabel',
      label: '显示Y轴标签',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    xAxisData: {
      name: 'xAxisData',
      label: 'X轴数据',
      setter: 'JsonSetter',
      defaultValue: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      group: '数据',
    },
    data: {
      name: 'data',
      label: '数据',
      setter: 'JsonSetter',
      defaultValue: [150, 230, 224, 218, 135, 147, 260],
      group: '数据',
    },
    option: {
      name: 'option',
      label: '高级配置(JSON)',
      setter: 'JsonSetter',
      defaultValue: {},
      group: '高级',
    },
  },
  events: [],
  defaultSize: {
    width: 400,
    height: 300,
  },
}

export default meta
