import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'DateRange',
  title: '日期范围选择',
  version: '1.0.0',
  category: '表单',
  props: {
    defaultValue: {
      name: 'defaultValue',
      label: '默认日期范围',
      setter: 'JsonSetter',
      defaultValue: [],
      group: '基础',
    },
    startPlaceholder: {
      name: 'startPlaceholder',
      label: '开始日期占位文本',
      setter: 'StringSetter',
      defaultValue: '开始日期',
      group: '基础',
    },
    endPlaceholder: {
      name: 'endPlaceholder',
      label: '结束日期占位文本',
      setter: 'StringSetter',
      defaultValue: '结束日期',
      group: '基础',
    },
    rangeSeparator: {
      name: 'rangeSeparator',
      label: '分隔符',
      setter: 'StringSetter',
      defaultValue: '至',
      group: '基础',
    },
    format: {
      name: 'format',
      label: '显示格式',
      setter: 'StringSetter',
      defaultValue: 'YYYY-MM-DD',
      group: '数据',
    },
    valueFormat: {
      name: 'valueFormat',
      label: '绑定值格式',
      setter: 'StringSetter',
      defaultValue: 'YYYY-MM-DD',
      group: '数据',
    },
    clearable: {
      name: 'clearable',
      label: '可清空',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '交互',
    },
    editable: {
      name: 'editable',
      label: '可手动输入',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '交互',
    },
    enableShortcuts: {
      name: 'enableShortcuts',
      label: '启用快捷选项',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '交互',
    },
    disabled: {
      name: 'disabled',
      label: '禁用',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '交互',
    },
    size: {
      name: 'size',
      label: '尺寸',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      defaultValue: 'default',
      group: '样式',
    },
    pickerWidth: {
      name: 'pickerWidth',
      label: '选择器宽度(%)',
      setter: 'NumberSetter',
      defaultValue: 100,
      group: '尺寸',
    },
    padding: {
      name: 'padding',
      label: '内边距',
      setter: 'NumberSetter',
      defaultValue: 8,
      group: '样式',
    },
    backgroundColor: {
      name: 'backgroundColor',
      label: '背景颜色',
      setter: 'ColorSetter',
      defaultValue: 'transparent',
      group: '样式',
    },
    opacity: {
      name: 'opacity',
      label: '不透明度',
      setter: 'SliderSetter',
      setterProps: {
        min: 0,
        max: 100,
        step: 1,
      },
      defaultValue: 100,
      group: '样式',
    },
    borderRadius: {
      name: 'borderRadius',
      label: '圆角',
      setter: 'NumberSetter',
      defaultValue: 4,
      group: '样式',
    },
    borderColor: {
      name: 'borderColor',
      label: '边框颜色',
      setter: 'ColorSetter',
      defaultValue: '#dcdfe6',
      group: '样式',
    },
  },
  events: ['onChange', 'onClear'],
  defaultSize: {
    width: 340,
    height: 40,
  },
}

export default meta
