import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'Container',
  title: '容器',
  version: '1.0.0',
  category: '布局容器',
  isContainer: true,
  props: {},
  styles: {
    // 尺寸
    width: {
      name: 'width',
      label: '宽度',
      title: '宽度',
      setter: 'StringSetter',
      defaultValue: '100%',
      description: '容器宽度，如 100%, 500px, auto',
      group: '尺寸',
    },
    height: {
      name: 'height',
      label: '高度',
      title: '高度',
      setter: 'StringSetter',
      defaultValue: 'auto',
      description: '容器高度，如 auto, 300px, 100vh',
      group: '尺寸',
    },
    minHeight: {
      name: 'minHeight',
      label: '最小高度',
      title: '最小高度',
      setter: 'StringSetter',
      defaultValue: '100px',
      description: '容器最小高度',
      group: '尺寸',
    },
    maxWidth: {
      name: 'maxWidth',
      label: '最大宽度',
      title: '最大宽度',
      setter: 'StringSetter',
      defaultValue: '',
      description: '容器最大宽度，如 1200px',
      group: '尺寸',
    },

    // 布局
    display: {
      name: 'display',
      label: '显示模式',
      title: '显示模式',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '块级', value: 'block' },
          { label: '弹性布局', value: 'flex' },
          { label: '网格布局', value: 'grid' },
          { label: '行内块', value: 'inline-block' },
        ],
      },
      defaultValue: 'block',
      description: '容器的布局模式',
      group: '布局',
    },
    flexDirection: {
      name: 'flexDirection',
      label: 'Flex方向',
      title: 'Flex方向',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '横向', value: 'row' },
          { label: '纵向', value: 'column' },
          { label: '横向反向', value: 'row-reverse' },
          { label: '纵向反向', value: 'column-reverse' },
        ],
      },
      defaultValue: 'row',
      description: 'Flex布局的主轴方向',
      group: '布局',
    },
    justifyContent: {
      name: 'justifyContent',
      label: '主轴对齐',
      title: '主轴对齐',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '起点', value: 'flex-start' },
          { label: '居中', value: 'center' },
          { label: '终点', value: 'flex-end' },
          { label: '两端对齐', value: 'space-between' },
          { label: '均匀分布', value: 'space-around' },
          { label: '等间距分布', value: 'space-evenly' },
        ],
      },
      defaultValue: 'flex-start',
      description: 'Flex容器主轴对齐方式',
      group: '布局',
    },
    alignItems: {
      name: 'alignItems',
      label: '交叉轴对齐',
      title: '交叉轴对齐',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '起点', value: 'flex-start' },
          { label: '居中', value: 'center' },
          { label: '终点', value: 'flex-end' },
          { label: '拉伸', value: 'stretch' },
          { label: '基线', value: 'baseline' },
        ],
      },
      defaultValue: 'flex-start',
      description: 'Flex容器交叉轴对齐方式',
      group: '布局',
    },
    flexWrap: {
      name: 'flexWrap',
      label: '换行',
      title: '换行',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '不换行', value: 'nowrap' },
          { label: '换行', value: 'wrap' },
          { label: '反向换行', value: 'wrap-reverse' },
        ],
      },
      defaultValue: 'nowrap',
      description: 'Flex项目是否换行',
      group: '布局',
    },
    gap: {
      name: 'gap',
      label: '间距',
      title: '间距',
      setter: 'StringSetter',
      defaultValue: '0',
      description: '子元素之间的间距，如 10px, 1rem',
      group: '布局',
    },

    // 间距
    padding: {
      name: 'padding',
      label: '内边距',
      title: '内边距',
      setter: 'StringSetter',
      defaultValue: '16px',
      description: '容器内边距，如 16px, 10px 20px',
      group: '间距',
    },
    margin: {
      name: 'margin',
      label: '外边距',
      title: '外边距',
      setter: 'StringSetter',
      defaultValue: '0',
      description: '容器外边距，如 0, 10px 20px',
      group: '间距',
    },

    // 外观
    backgroundColor: {
      name: 'backgroundColor',
      label: '背景颜色',
      title: '背景颜色',
      setter: 'ColorSetter',
      defaultValue: 'transparent',
      description: '容器背景颜色',
      group: '外观',
    },
    backgroundImage: {
      name: 'backgroundImage',
      label: '背景图片',
      title: '背景图片',
      setter: 'StringSetter',
      defaultValue: '',
      description: '背景图片URL，如 url(image.jpg)',
      group: '外观',
    },
    backgroundSize: {
      name: 'backgroundSize',
      label: '背景尺寸',
      title: '背景尺寸',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '覆盖', value: 'cover' },
          { label: '包含', value: 'contain' },
          { label: '自动', value: 'auto' },
        ],
      },
      defaultValue: 'cover',
      group: '外观',
    },
    borderRadius: {
      name: 'borderRadius',
      label: '圆角',
      title: '圆角',
      setter: 'StringSetter',
      defaultValue: '0',
      description: '容器圆角，如 4px, 10px 20px',
      group: '外观',
    },
    borderWidth: {
      name: 'borderWidth',
      label: '边框宽度',
      title: '边框宽度',
      setter: 'StringSetter',
      defaultValue: '0',
      description: '边框宽度，如 1px',
      group: '外观',
    },
    borderColor: {
      name: 'borderColor',
      label: '边框颜色',
      title: '边框颜色',
      setter: 'ColorSetter',
      defaultValue: '#dcdfe6',
      description: '边框颜色',
      group: '外观',
    },
    borderStyle: {
      name: 'borderStyle',
      label: '边框样式',
      title: '边框样式',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '实线', value: 'solid' },
          { label: '虚线', value: 'dashed' },
          { label: '点线', value: 'dotted' },
          { label: '无', value: 'none' },
        ],
      },
      defaultValue: 'solid',
      description: '边框样式',
      group: '外观',
    },
    boxShadow: {
      name: 'boxShadow',
      label: '阴影',
      title: '阴影',
      setter: 'StringSetter',
      defaultValue: '',
      description: '盒子阴影，如 0 2px 8px rgba(0,0,0,0.1)',
      group: '外观',
    },
    opacity: {
      name: 'opacity',
      label: '透明度',
      title: '透明度',
      setter: 'NumberSetter',
      setterProps: {
        min: 0,
        max: 1,
        step: 0.1,
      },
      defaultValue: 1,
      description: '容器透明度，0-1',
      group: '外观',
    },

    // 定位
    position: {
      name: 'position',
      label: '定位方式',
      title: '定位方式',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '静态', value: 'static' },
          { label: '相对', value: 'relative' },
          { label: '绝对', value: 'absolute' },
          { label: '固定', value: 'fixed' },
          { label: '粘性', value: 'sticky' },
        ],
      },
      defaultValue: 'relative',
      description: 'CSS定位方式',
      group: '定位',
    },
    zIndex: {
      name: 'zIndex',
      label: 'Z轴层级',
      title: 'Z轴层级',
      setter: 'NumberSetter',
      defaultValue: 0,
      description: '容器的层叠顺序',
      group: '定位',
    },

    // 溢出
    overflow: {
      name: 'overflow',
      label: '溢出处理',
      title: '溢出处理',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '可见', value: 'visible' },
          { label: '隐藏', value: 'hidden' },
          { label: '滚动', value: 'scroll' },
          { label: '自动', value: 'auto' },
        ],
      },
      defaultValue: 'visible',
      description: '内容溢出时的处理方式',
      group: '其他',
    },
  },
  events: [],
  defaultSize: {
    width: 300,
    height: 200,
  },
}

export default meta
