import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'FunnelChart',
  title: '漏斗图',
  version: '1.0.0',
  category: '图表',
  props: {
    title: {
      name: 'title',
      label: '图表标题',
      setter: 'StringSetter',
      defaultValue: '',
      group: '基础',
    },
    seriesName: {
      name: 'seriesName',
      label: '系列名称',
      setter: 'StringSetter',
      defaultValue: 'Funnel',
      group: '基础',
    },
    sort: {
      name: 'sort',
      label: '排序方式',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '降序', value: 'descending' },
          { label: '升序', value: 'ascending' },
          { label: '无', value: 'none' },
        ],
      },
      defaultValue: 'descending',
      group: '样式',
    },
    gap: {
      name: 'gap',
      label: '间距',
      setter: 'NumberSetter',
      defaultValue: 2,
      group: '样式',
    },
    left: {
      name: 'left',
      label: '左侧位置',
      setter: 'StringSetter',
      defaultValue: '10%',
      group: '位置',
    },
    top: {
      name: 'top',
      label: '顶部位置',
      setter: 'StringSetter',
      defaultValue: '20%',
      group: '位置',
    },
    bottom: {
      name: 'bottom',
      label: '底部位置',
      setter: 'StringSetter',
      defaultValue: '20%',
      group: '位置',
    },
    width: {
      name: 'width',
      label: '宽度',
      setter: 'StringSetter',
      defaultValue: '80%',
      group: '位置',
    },
    min: {
      name: 'min',
      label: '最小值',
      setter: 'NumberSetter',
      defaultValue: 0,
      group: '数据',
    },
    max: {
      name: 'max',
      label: '最大值',
      setter: 'NumberSetter',
      defaultValue: 100,
      group: '数据',
    },
    minSize: {
      name: 'minSize',
      label: '最小尺寸',
      setter: 'StringSetter',
      defaultValue: '0%',
      group: '样式',
    },
    maxSize: {
      name: 'maxSize',
      label: '最大尺寸',
      setter: 'StringSetter',
      defaultValue: '100%',
      group: '样式',
    },
    showLabel: {
      name: 'showLabel',
      label: '显示标签',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '标签',
    },
    labelPosition: {
      name: 'labelPosition',
      label: '标签位置',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
          { label: '内部', value: 'inside' },
        ],
      },
      defaultValue: 'inside',
      group: '标签',
    },
    labelFormatter: {
      name: 'labelFormatter',
      label: '标签格式',
      setter: 'StringSetter',
      defaultValue: '{b}: {c}',
      group: '标签',
    },
    showLabelLine: {
      name: 'showLabelLine',
      label: '显示标签线',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '标签',
    },
    labelLineLength: {
      name: 'labelLineLength',
      label: '标签线长度',
      setter: 'NumberSetter',
      defaultValue: 10,
      group: '标签',
    },
    borderColor: {
      name: 'borderColor',
      label: '边框颜色',
      setter: 'ColorSetter',
      defaultValue: '#fff',
      group: '样式',
    },
    borderWidth: {
      name: 'borderWidth',
      label: '边框宽度',
      setter: 'NumberSetter',
      defaultValue: 1,
      group: '样式',
    },
    data: {
      name: 'data',
      label: '数据',
      setter: 'JsonSetter',
      defaultValue: [
        { name: '阶段1', value: 100 },
        { name: '阶段2', value: 80 },
        { name: '阶段3', value: 60 },
      ],
      group: '数据',
    },
    option: {
      name: 'option',
      label: '高级配置(JSON)',
      setter: 'JsonSetter',
      defaultValue: {},
      group: '高级',
    },
  },
  events: [],
  defaultSize: {
    width: 400,
    height: 300,
  },
}

export default meta
