import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'TextareaInput',
  title: '多行文本',
  version: '1.0.0',
  category: '表单',
  props: {
    modelValue: {
      name: 'modelValue',
      label: '默认值',
      title: '默认值',
      setter: 'StringSetter',
      defaultValue: '',
      group: '基础',
    },
    placeholder: {
      name: 'placeholder',
      label: '占位文本',
      title: '占位文本',
      setter: 'StringSetter',
      defaultValue: '请输入',
      group: '基础',
    },
    rows: {
      name: 'rows',
      label: '行数',
      title: '行数',
      setter: 'NumberSetter',
      defaultValue: 4,
      group: '基础',
    },
    autosize: {
      name: 'autosize',
      label: '自动高度',
      title: '自动高度',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '交互',
    },
    disabled: {
      name: 'disabled',
      label: '禁用',
      title: '禁用',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '交互',
    },
    size: {
      name: 'size',
      label: '尺寸',
      title: '尺寸',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      defaultValue: 'default',
      group: '样式',
    },
    maxlength: {
      name: 'maxlength',
      label: '最大长度',
      title: '最大长度',
      setter: 'NumberSetter',
      defaultValue: 0,
      group: '交互',
    },
    showWordLimit: {
      name: 'showWordLimit',
      label: '显示字数统计',
      title: '显示字数统计',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '交互',
    },
    resize: {
      name: 'resize',
      label: '可调整方向',
      title: '可调整方向',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '垂直', value: 'vertical' },
          { label: '水平', value: 'horizontal' },
          { label: '双向', value: 'both' },
          { label: '禁用', value: 'none' },
        ],
      },
      defaultValue: 'vertical',
      group: '样式',
    },
    inputWidth: {
      name: 'inputWidth',
      label: '输入框宽度',
      title: '输入框宽度',
      setter: 'NumberSetter',
      defaultValue: 100,
      description: '宽度百分比 (0-100)',
      group: '尺寸',
    },
    padding: {
      name: 'padding',
      label: '内边距',
      title: '内边距',
      setter: 'NumberSetter',
      defaultValue: 8,
      group: '尺寸',
    },
    backgroundColor: {
      name: 'backgroundColor',
      label: '背景颜色',
      title: '背景颜色',
      setter: 'ColorSetter',
      defaultValue: 'transparent',
      group: '样式',
    },
    borderRadius: {
      name: 'borderRadius',
      label: '圆角',
      title: '圆角',
      setter: 'NumberSetter',
      defaultValue: 4,
      group: '样式',
    },
    opacity: {
      name: 'opacity',
      label: '不透明度',
      title: '不透明度',
      setter: 'SliderSetter',
      setterProps: {
        min: 0,
        max: 100,
        step: 1,
      },
      defaultValue: 100,
      group: '样式',
    },
  },
  events: ['onInput', 'onChange'],
  defaultSize: {
    width: 260,
    height: 120,
  },
}

export default meta
