import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'Slider',
  componentName: 'Slider',
  title: '滑块',
  version: '1.0.0',
  category: '基础控件',
  props: {
    min: {
      name: 'min',
      label: '最小值',
      title: '最小值',
      setter: 'NumberSetter',
      defaultValue: 0,
      group: '数据',
    },
    max: {
      name: 'max',
      label: '最大值',
      title: '最大值',
      setter: 'NumberSetter',
      defaultValue: 100,
      group: '数据',
    },
    step: {
      name: 'step',
      label: '步长',
      title: '步长',
      setter: 'NumberSetter',
      defaultValue: 1,
      group: '数据',
    },
    defaultValue: {
      name: 'defaultValue',
      label: '默认值',
      title: '默认值',
      setter: 'NumberSetter',
      defaultValue: 0,
      group: '基础',
    },
    showInput: {
      name: 'showInput',
      label: '显示输入框',
      title: '显示输入框',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '显示',
    },
    showInputControls: {
      name: 'showInputControls',
      label: '显示控制按钮',
      title: '显示控制按钮',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '显示',
    },
    showStops: {
      name: 'showStops',
      label: '显示间断点',
      title: '显示间断点',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '显示',
    },
    showTooltip: {
      name: 'showTooltip',
      label: '显示提示',
      title: '显示提示',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '显示',
    },
    range: {
      name: 'range',
      label: '范围选择',
      title: '范围选择',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '交互',
    },
    vertical: {
      name: 'vertical',
      label: '垂直模式',
      title: '垂直模式',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '布局',
    },
    height: {
      name: 'height',
      label: '垂直模式高度',
      title: '垂直模式高度',
      setter: 'StringSetter',
      defaultValue: '200px',
      group: '尺寸',
    },
    padding: {
      name: 'padding',
      label: '内边距',
      title: '内边距',
      setter: 'NumberSetter',
      defaultValue: 16,
      group: '样式',
    },
    backgroundColor: {
      name: 'backgroundColor',
      label: '背景颜色',
      title: '背景颜色',
      setter: 'ColorSetter',
      defaultValue: 'transparent',
      group: '样式',
    },
    activeColor: {
      name: 'activeColor',
      label: '激活颜色',
      title: '激活颜色',
      setter: 'ColorSetter',
      defaultValue: '#409eff',
      group: '样式',
    },
    inactiveColor: {
      name: 'inactiveColor',
      label: '未激活颜色',
      title: '未激活颜色',
      setter: 'ColorSetter',
      defaultValue: '#e4e7ed',
      group: '样式',
    },
    showValue: {
      name: 'showValue',
      label: '显示数值',
      title: '显示数值',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '显示',
    },
    valueColor: {
      name: 'valueColor',
      label: '数值颜色',
      title: '数值颜色',
      setter: 'ColorSetter',
      defaultValue: '#606266',
      group: '样式',
    },
  },
  events: ['onChange'],
  defaultSize: {
    width: 300,
    height: 40,
  },
}

export default meta
