import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'GaugeChart',
  componentName: 'GaugeChart',
  title: '仪表盘',
  version: '1.0.0',
  category: '图表',
  props: {
    title: {
      name: 'title',
      label: '图表标题',
      setter: 'StringSetter',
      defaultValue: '',
      group: '基础',
    },
    value: {
      name: 'value',
      label: '数值',
      setter: 'NumberSetter',
      defaultValue: 75,
      group: '数据',
    },
    name: {
      name: 'name',
      label: '名称',
      setter: 'StringSetter',
      defaultValue: '完成率',
      group: '基础',
    },
    min: {
      name: 'min',
      label: '最小值',
      setter: 'NumberSetter',
      defaultValue: 0,
      group: '数据',
    },
    max: {
      name: 'max',
      label: '最大值',
      setter: 'NumberSetter',
      defaultValue: 100,
      group: '数据',
    },
    startAngle: {
      name: 'startAngle',
      label: '起始角度',
      setter: 'NumberSetter',
      defaultValue: 225,
      group: '样式',
    },
    endAngle: {
      name: 'endAngle',
      label: '结束角度',
      setter: 'NumberSetter',
      defaultValue: -45,
      group: '样式',
    },
    splitNumber: {
      name: 'splitNumber',
      label: '分割段数',
      setter: 'NumberSetter',
      defaultValue: 10,
      group: '样式',
    },
    showProgress: {
      name: 'showProgress',
      label: '显示进度条',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '进度',
    },
    progressWidth: {
      name: 'progressWidth',
      label: '进度条宽度',
      setter: 'NumberSetter',
      defaultValue: 10,
      group: '进度',
    },
    axisLineWidth: {
      name: 'axisLineWidth',
      label: '轴线宽度',
      setter: 'NumberSetter',
      defaultValue: 10,
      group: '轴线',
    },
    axisLineColor: {
      name: 'axisLineColor',
      label: '轴线颜色配置',
      setter: 'JsonSetter',
      defaultValue: [
        [0.3, '#67e0e3'],
        [0.7, '#37a2da'],
        [1, '#fd666d'],
      ],
      group: '轴线',
    },
    pointerColor: {
      name: 'pointerColor',
      label: '指针颜色',
      setter: 'ColorSetter',
      defaultValue: 'auto',
      group: '指针',
    },
    pointerLength: {
      name: 'pointerLength',
      label: '指针长度',
      setter: 'StringSetter',
      defaultValue: '70%',
      group: '指针',
    },
    pointerWidth: {
      name: 'pointerWidth',
      label: '指针宽度',
      setter: 'NumberSetter',
      defaultValue: 8,
      group: '指针',
    },
    showAxisTick: {
      name: 'showAxisTick',
      label: '显示刻度',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '刻度',
    },
    axisTickSplitNumber: {
      name: 'axisTickSplitNumber',
      label: '刻度分割数',
      setter: 'NumberSetter',
      defaultValue: 5,
      group: '刻度',
    },
    showSplitLine: {
      name: 'showSplitLine',
      label: '显示分割线',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '刻度',
    },
    splitLineLength: {
      name: 'splitLineLength',
      label: '分割线长度',
      setter: 'NumberSetter',
      defaultValue: 15,
      group: '刻度',
    },
    showAxisLabel: {
      name: 'showAxisLabel',
      label: '显示轴标签',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '标签',
    },
    axisLabelDistance: {
      name: 'axisLabelDistance',
      label: '标签距离',
      setter: 'NumberSetter',
      defaultValue: 25,
      group: '标签',
    },
    axisLabelFontSize: {
      name: 'axisLabelFontSize',
      label: '标签字号',
      setter: 'NumberSetter',
      defaultValue: 12,
      group: '标签',
    },
    detailFormatter: {
      name: 'detailFormatter',
      label: '详情格式',
      setter: 'StringSetter',
      defaultValue: '{value}',
      group: '详情',
    },
    detailFontSize: {
      name: 'detailFontSize',
      label: '详情字号',
      setter: 'NumberSetter',
      defaultValue: 20,
      group: '详情',
    },
    detailOffsetX: {
      name: 'detailOffsetX',
      label: '详情X偏移',
      setter: 'StringSetter',
      defaultValue: '0%',
      group: '详情',
    },
    detailOffsetY: {
      name: 'detailOffsetY',
      label: '详情Y偏移',
      setter: 'StringSetter',
      defaultValue: '70%',
      group: '详情',
    },
    option: {
      name: 'option',
      label: '高级配置(JSON)',
      setter: 'JsonSetter',
      defaultValue: {},
      group: '高级',
    },
  },
  events: [],
  defaultSize: {
    width: 300,
    height: 300,
  },
}

export default meta
