import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'StackedBarChart',
  componentName: 'StackedBarChart',
  title: '堆叠柱状图',
  version: '1.0.0',
  category: '图表',
  props: {
    title: {
      name: 'title',
      label: '图表标题',
      setter: 'StringSetter',
      defaultValue: '',
      group: '基础',
    },
    colors: {
      name: 'colors',
      label: '颜色列表',
      setter: 'JsonSetter',
      defaultValue: ['#5470c6', '#91cc75', '#fac858'],
      group: '样式',
    },
    showLegend: {
      name: 'showLegend',
      label: '显示图例',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '图例',
    },
    legendPosition: {
      name: 'legendPosition',
      label: '图例位置',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '顶部', value: 'top' },
          { label: '底部', value: 'bottom' },
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
        ],
      },
      defaultValue: 'top',
      group: '图例',
    },
    showTooltip: {
      name: 'showTooltip',
      label: '显示提示',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '交互',
    },
    showGrid: {
      name: 'showGrid',
      label: '显示网格',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    xAxisName: {
      name: 'xAxisName',
      label: 'X轴名称',
      setter: 'StringSetter',
      defaultValue: '',
      group: '坐标轴',
    },
    yAxisName: {
      name: 'yAxisName',
      label: 'Y轴名称',
      setter: 'StringSetter',
      defaultValue: '',
      group: '坐标轴',
    },
    showXAxisLine: {
      name: 'showXAxisLine',
      label: '显示X轴线',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    showXAxisLabel: {
      name: 'showXAxisLabel',
      label: '显示X轴标签',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    showYAxisLine: {
      name: 'showYAxisLine',
      label: '显示Y轴线',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    showYAxisLabel: {
      name: 'showYAxisLabel',
      label: '显示Y轴标签',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '坐标轴',
    },
    barWidth: {
      name: 'barWidth',
      label: '柱宽度',
      setter: 'StringSetter',
      defaultValue: '60%',
      group: '样式',
    },
    borderRadius: {
      name: 'borderRadius',
      label: '柱圆角',
      setter: 'NumberSetter',
      defaultValue: 0,
      group: '样式',
    },
    showLabel: {
      name: 'showLabel',
      label: '显示数据标签',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '标签',
    },
    xAxisData: {
      name: 'xAxisData',
      label: 'X轴数据',
      setter: 'JsonSetter',
      defaultValue: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      group: '数据',
    },
    seriesNames: {
      name: 'seriesNames',
      label: '系列名称',
      setter: 'JsonSetter',
      defaultValue: ['Series 1', 'Series 2', 'Series 3'],
      group: '数据',
    },
    seriesData: {
      name: 'seriesData',
      label: '系列数据',
      setter: 'JsonSetter',
      defaultValue: [
        [120, 132, 101, 134, 90, 230, 210],
        [220, 182, 191, 234, 290, 330, 310],
        [150, 232, 201, 154, 190, 330, 410],
      ],
      group: '数据',
    },
    option: {
      name: 'option',
      label: '高级配置(JSON)',
      setter: 'JsonSetter',
      defaultValue: {},
      group: '高级',
    },
  },
  events: [],
  defaultSize: {
    width: 400,
    height: 300,
  },
}

export default meta
