import type { MaterialMeta } from '@vela/core/types'

const meta: MaterialMeta = {
  name: 'Select',
  componentName: 'Select',
  title: '下拉选择',
  version: '1.0.0',
  category: '基础控件',
  props: {
    options: {
      name: 'options',
      label: '选项数据',
      title: '选项数据',
      setter: 'JsonSetter',
      defaultValue: [],
      group: '数据',
    },
    defaultValue: {
      name: 'defaultValue',
      label: '默认值',
      title: '默认值',
      setter: 'StringSetter',
      defaultValue: '',
      group: '基础',
    },
    placeholder: {
      name: 'placeholder',
      label: '占位文本',
      title: '占位文本',
      setter: 'StringSetter',
      defaultValue: '请选择',
      group: '基础',
    },
    clearable: {
      name: 'clearable',
      label: '可清空',
      title: '可清空',
      setter: 'BooleanSetter',
      defaultValue: true,
      group: '交互',
    },
    filterable: {
      name: 'filterable',
      label: '可搜索',
      title: '可搜索',
      setter: 'BooleanSetter',
      defaultValue: false,
      group: '交互',
    },
    size: {
      name: 'size',
      label: '尺寸',
      title: '尺寸',
      setter: 'SelectSetter',
      setterProps: {
        options: [
          { label: '大', value: 'large' },
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      defaultValue: 'default',
      group: '样式',
    },
    labelField: {
      name: 'labelField',
      label: '标签字段名',
      title: '标签字段名',
      setter: 'StringSetter',
      defaultValue: 'label',
      group: '数据',
    },
    valueField: {
      name: 'valueField',
      label: '值字段名',
      title: '值字段名',
      setter: 'StringSetter',
      defaultValue: 'value',
      group: '数据',
    },
    emptyText: {
      name: 'emptyText',
      label: '空数据文本',
      title: '空数据文本',
      setter: 'StringSetter',
      defaultValue: '暂无选项',
      group: '基础',
    },
    selectWidth: {
      name: 'selectWidth',
      label: '选择器宽度',
      title: '选择器宽度',
      setter: 'NumberSetter',
      defaultValue: 100,
      description: '宽度百分比 (0-100)',
      group: '尺寸',
    },
    padding: {
      name: 'padding',
      label: '内边距',
      title: '内边距',
      setter: 'NumberSetter',
      defaultValue: 8,
      group: '尺寸',
    },
    backgroundColor: {
      name: 'backgroundColor',
      label: '背景颜色',
      title: '背景颜色',
      setter: 'ColorSetter',
      defaultValue: 'transparent',
      group: '样式',
    },
    borderRadius: {
      name: 'borderRadius',
      label: '圆角',
      title: '圆角',
      setter: 'NumberSetter',
      defaultValue: 4,
      group: '样式',
    },
    borderColor: {
      name: 'borderColor',
      label: '边框颜色',
      title: '边框颜色',
      setter: 'ColorSetter',
      defaultValue: '#dcdfe6',
      group: '样式',
    },
    focusBorderColor: {
      name: 'focusBorderColor',
      label: '聚焦边框色',
      title: '聚焦边框色',
      setter: 'ColorSetter',
      defaultValue: '#409eff',
      group: '样式',
    },
    hoverBorderColor: {
      name: 'hoverBorderColor',
      label: '悬停边框色',
      title: '悬停边框色',
      setter: 'ColorSetter',
      defaultValue: '#c0c4cc',
      group: '样式',
    },
    opacity: {
      name: 'opacity',
      label: '不透明度',
      title: '不透明度',
      setter: 'SliderSetter',
      setterProps: {
        min: 0,
        max: 100,
        step: 1,
      },
      defaultValue: 100,
      group: '样式',
    },
  },
  events: ['onChange', 'onClear'],
  defaultSize: {
    width: 200,
    height: 40,
  },
}

export default meta
